[workspace]
members = ["conformance"]
resolver = "3"

[workspace.package]
version = "0.1.1"
edition = "2024"
license = "MIT"
publish = false

[workspace.dependencies]
binja_wasm = { path = ".", default-features = false }
binaryninja = { git = "https://github.com/Vector35/binaryninja-api.git", tag = "stable/6.0.10601", default-features = false }
binaryninjacore-sys = { git = "https://github.com/Vector35/binaryninja-api.git", tag = "stable/6.0.10601", default-features = false }
tracing = "0.1"
wasmparser = { version = "0.255.0", default-features = false }
wat = { version = "1.254.0", default-features = false }
wast = "254.0.0"
gimli = { version = "0.31", default-features = false }

[package]
name = "binja_wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["core"]
core = ["binaryninja/core", "binaryninjacore-sys/core"]

[dependencies]
binaryninja.workspace = true
binaryninjacore-sys.workspace = true
tracing.workspace = true
wasmparser = { workspace = true, features = ["features", "simd", "component-model"] }
wat = { workspace = true, features = ["component-model"] }
gimli = { workspace = true, features = ["read", "std"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
