[package]
name = "conformance"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = ["core"]
core = ["binja_wasm/core", "binaryninjacore-sys/core"]

[dependencies]
binja_wasm.workspace = true
binaryninjacore-sys.workspace = true
wasmparser = { workspace = true, default-features = true, features = ["features", "simd", "validate"] }
wast.workspace = true
wat = { workspace = true, default-features = true }
